import {
  startPipeline,
  getPipeline
} from "./api";

const wait = (ms) =>
  new Promise((resolve) =>
    setTimeout(resolve, ms)
  );

function convertStatus(status) {
  if (status === "SUCCESS") {
    return "done";
  }

  if (status === "RUNNING") {
    return "active";
  }

  return "";
}

function updateFrontendStages(
  backendStages,
  currentStages
) {
  const stageMap = {
    Checkout: "analyze",
    Build: "lang",
    Docker: "docker",
    Terraform: "tf",
    Deploy: "cost"
  };

  return currentStages.map(
    (stage) => {
      const backendName =
        Object.keys(stageMap)
          .find(
            (name) =>
              stageMap[name] ===
              stage.id
          );

      const backendStage =
        backendStages.find(
          (item) =>
            item.name ===
            backendName
        );

      if (!backendStage) {
        return stage;
      }

      return {
        ...stage,

        status:
          convertStatus(
            backendStage.status
          )
      };
    }
  );
}

export async function runPipeline(
  repoUrl,
  onUpdate
) {
  // Import stages dynamically so this file
  // is responsible only for API communication.
  const { STAGES } =
    await import(
      "../data/stages.js"
    );

  // Start backend pipeline
  const response =
    await startPipeline(
      repoUrl,
      "main"
    );

  const backendPipeline =
    response.data;

  const artifacts =
    backendPipeline.artifacts;

  let state = {
    repoName:
      artifacts.analysis.repository,

    serviceName:
      artifacts.analysis.repository
        .split("/")
        .pop(),

    lang: {
      name:
        artifacts.analysis.language.name,

      tag:
        artifacts.analysis.language.version,

      manifest:
        artifacts.analysis.language.manifest,

      icon:
        artifacts.analysis.language.name
          .substring(0, 2)
          .toUpperCase(),

      dockerfile:
        artifacts.docker.dockerfile
    },

    k8sYaml:
      artifacts.kubernetes.manifest,

    tf:
      artifacts.terraform.terraform,

    tfLogs: [
      "Terraform plan generated by backend"
    ],

    stages:
      STAGES.map(
        (stage) => ({
          ...stage,
          status: ""
        })
      ),

    pipelineId:
      backendPipeline.id,

    serviceName:
      backendPipeline
        .artifacts
        .terraform
        .serviceName
  };

  // Show initial state
  onUpdate({
    ...state
  });

  // Poll backend
  let finished = false;

  while (!finished) {
    await wait(1000);

    const result =
      await getPipeline(
        backendPipeline.id
      );

    const updated =
      result.data;

    state = {
      ...state,

      stages:
        updateFrontendStages(
          updated.stages,
          state.stages
        )
    };

    onUpdate({
      ...state
    });

    finished =
      updated.status ===
        "SUCCESS" ||
      updated.status ===
        "FAILED";
  }

  return state;
}